"""change unique constraints to per-org

Revision ID: 96a5f2236d1e
Revises: 
Create Date: 2025-11-19 13:47:39.703341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a5f2236d1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_client_name_org_uc', 'clients', ['name', 'organization_id'])
    op.drop_index('ix_users_employee_id', table_name='users')
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=False)
    op.create_unique_constraint('_user_employee_org_uc', 'users', ['employee_id', 'organization_id'])
    op.drop_constraint('vehicles_license_plate_key', 'vehicles', type_='unique')
    op.drop_index('ix_vehicles_telemetry_device_id', table_name='vehicles')
    op.create_index(op.f('ix_vehicles_telemetry_device_id'), 'vehicles', ['telemetry_device_id'], unique=False)
    op.create_unique_constraint('_vehicle_identifier_org_uc', 'vehicles', ['identifier', 'organization_id'])
    op.create_unique_constraint('_vehicle_license_org_uc', 'vehicles', ['license_plate', 'organization_id'])
    op.create_unique_constraint('_vehicle_telemetry_org_uc', 'vehicles', ['telemetry_device_id', 'organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_vehicle_telemetry_org_uc', 'vehicles', type_='unique')
    op.drop_constraint('_vehicle_license_org_uc', 'vehicles', type_='unique')
    op.drop_constraint('_vehicle_identifier_org_uc', 'vehicles', type_='unique')
    op.drop_index(op.f('ix_vehicles_telemetry_device_id'), table_name='vehicles')
    op.create_index('ix_vehicles_telemetry_device_id', 'vehicles', ['telemetry_device_id'], unique=True)
    op.create_unique_constraint('vehicles_license_plate_key', 'vehicles', ['license_plate'])
    op.drop_constraint('_user_employee_org_uc', 'users', type_='unique')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.create_index('ix_users_employee_id', 'users', ['employee_id'], unique=True)
    op.drop_constraint('_client_name_org_uc', 'clients', type_='unique')
    # ### end Alembic commands ###
