"""Add address columns to clients

Revision ID: 9c77ccc94435
Revises: 96a5f2236d1e
Create Date: 2025-11-21 21:11:12.542001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c77ccc94435'
down_revision: Union[str, None] = '96a5f2236d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('cep', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('address_street', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('address_number', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('address_neighborhood', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('address_city', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('address_state', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'address_state')
    op.drop_column('clients', 'address_city')
    op.drop_column('clients', 'address_neighborhood')
    op.drop_column('clients', 'address_number')
    op.drop_column('clients', 'address_street')
    op.drop_column('clients', 'cep')
    # ### end Alembic commands ###
