"""make component_removed_id nullable

Revision ID: b87be19dfb5b
Revises: 30b19e808802
Create Date: 2025-11-18 10:19:52.196829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87be19dfb5b'
down_revision: Union[str, None] = '30b19e808802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_requests', sa.Column('maintenance_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_requests', 'maintenance_type')
    # ### end Alembic commands ###
